
modLoader="javafml"
loaderVersion="${loader_version_range}"
license="LGPL-3.0-only"
issueTrackerURL="https://github.com/Yuqi154/NeOculus/issues"

[[mods]]
modId="oculus"
version="${mod_version}"
displayURL="https://www.curseforge.com/minecraft/mc-mods/forgeoculus"
displayName="ForgeOculus"
provides=["iris"]
logoFile="forgeoculus-logo.png"

authors="NanoLive, dima_dencep, coderbot, IMS212, Justsnoopy30, FoundationGames, Yuqi154, Peak885, Basdxz"
description='''
Unofficial Fork of "Oculus", made to work with neoforge 1.21+
Unofficial Fork of "Iris", made to work with FML
'''

[[mixins]]
config="mixins.oculus.json"
[[mixins]]
config="mixins.oculus.vertexformat.json"
[[mixins]]
config="mixins.oculus.bettermipmaps.json"
[[mixins]]
config="mixins.oculus.fixes.maxfpscrash.json"
[[mixins]]
config="oculus-batched-entity-rendering.mixins.json"
[[mixins]]
config="mixins.oculus.compat.embeddium.json"

[[accessTransformers]]
file="META-INF/accesstransformer.cfg"

# The coremods config file path is not configurable and is always loaded from META-INF/coremods.json

# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.oculus]]
    modId="forge" # Changed from neoforge
    mandatory = true
    versionRange="${forge_version_range}" # Use the variable from your properties
    ordering="NONE"
    side="BOTH"

[[dependencies.oculus]]
    modId="minecraft"
    mandatory = true
    versionRange="[1.21.1]"
    ordering="NONE"
    side="BOTH"

[[dependencies.oculus]]
    modId = "beddium"
    mandatory = true
    versionRange = "[1.0.0,)"
    ordering = "AFTER"
    side = "CLIENT"